set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

bind-key Q confirm-before -p "關閉整個 ide (#S)? (y/n)" kill-session

set -g status-left-length 20
set -g status-right-length 200
set -g status-right "#[fg=colour231,bg=colour24,bold] C-b 方向鍵切pane  z縮放  Q關閉ide  d離開 #[default]"
